### ISSUE TITLE
Rename `TTypes.grid_position`

### ISSUE THREAD

**Issue by SirWerto** [TheRedNatar/Mi-intento-final-de-Travian#7]
`TTypes.grid_position` is not well named, indeed, it is misleading as it is the identifier of the poisition(I think). So, propose a new name an modify it everywhere.

Posible names:
- map_id
- position_id

**Comment by Yashdon999** [comment]
I Would like to fix this issue

**Comment by SirWerto** [comment]
Nice :100:  , feel free to open a PR and don't hesitate to ask if you have questions.

**Comment by SirWerto** [comment]
Thanks for the contribution!!!! ❤️ 🧡 💛 💚 💙 💜 🖤 🤍 🤎
